// This file is auto-generated by AssetsPostprocessor.
// Do not modify this file manually.
//
// To regenerate this file manually, select the menu item Tools > LunarFramework > Generate R.cs.
//

using Luna;
using UnityEngine;

namespace R
{
    public static class Audios
    {
        public static Asset<AudioClip> タンホイザーとアイーダメドレー => new("Assets/Game/Common/Commend/Audios/タンホイザーとアイーダメドレー.mp3");
        public static Asset<AudioClip> ハレルヤ => new("Assets/Game/Common/Commend/Audios/ハレルヤ.mp3");
        public static Asset<AudioClip> 威風堂々 => new("Assets/Game/Common/Commend/Audios/威風堂々.mp3");
        public static Asset<AudioClip> 拍手 => new("Assets/Game/Common/Commend/Audios/拍手.mp3");
        public static Asset<AudioClip> 指笛 => new("Assets/Game/Common/Commend/Audios/指笛.mp3");
        public static Asset<AudioClip> 歓声 => new("Assets/Game/Common/Commend/Audios/歓声.mp3");
        public static Asset<AudioClip> 見よ勇者は帰る => new("Assets/Game/Common/Commend/Audios/見よ、勇者は帰る.mp3");
        public static Asset<AudioClip> _01Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/01_gal.mp3");
        public static Asset<AudioClip> _02Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/02_gal.mp3");
        public static Asset<AudioClip> _03Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/03_gal.mp3");
        public static Asset<AudioClip> _04Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/04_gal.mp3");
        public static Asset<AudioClip> _05Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/05_gal.mp3");
        public static Asset<AudioClip> _06Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/06_gal.mp3");
        public static Asset<AudioClip> _07Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/07_gal.mp3");
        public static Asset<AudioClip> _08Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/08_gal.mp3");
        public static Asset<AudioClip> _09Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/09_gal.mp3");
        public static Asset<AudioClip> _10Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/10_gal.mp3");
        public static Asset<AudioClip> _11Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/11_gal.mp3");
        public static Asset<AudioClip> _12Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/12_gal.mp3");
        public static Asset<AudioClip> _13Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/13_gal.mp3");
        public static Asset<AudioClip> _14Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/14_gal.mp3");
        public static Asset<AudioClip> _15Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/15_gal.mp3");
        public static Asset<AudioClip> _16Gal => new("Assets/Game/Janken/Spine/Characters/Gal/mc/16_gal.mp3");
        public static Asset<AudioClip> _01King => new("Assets/Game/Janken/Spine/Characters/King/mc/01_king.mp3");
        public static Asset<AudioClip> _02King => new("Assets/Game/Janken/Spine/Characters/King/mc/02_king.mp3");
        public static Asset<AudioClip> _03King => new("Assets/Game/Janken/Spine/Characters/King/mc/03_king.mp3");
        public static Asset<AudioClip> _04King => new("Assets/Game/Janken/Spine/Characters/King/mc/04_king.mp3");
        public static Asset<AudioClip> _05King => new("Assets/Game/Janken/Spine/Characters/King/mc/05_king.mp3");
        public static Asset<AudioClip> _06King => new("Assets/Game/Janken/Spine/Characters/King/mc/06_king.mp3");
        public static Asset<AudioClip> _07King => new("Assets/Game/Janken/Spine/Characters/King/mc/07_king.mp3");
        public static Asset<AudioClip> _08King => new("Assets/Game/Janken/Spine/Characters/King/mc/08_king.mp3");
        public static Asset<AudioClip> _09King => new("Assets/Game/Janken/Spine/Characters/King/mc/09_king.mp3");
        public static Asset<AudioClip> _10King => new("Assets/Game/Janken/Spine/Characters/King/mc/10_king.mp3");
        public static Asset<AudioClip> _11King => new("Assets/Game/Janken/Spine/Characters/King/mc/11_king.mp3");
        public static Asset<AudioClip> _12King => new("Assets/Game/Janken/Spine/Characters/King/mc/12_king.mp3");
        public static Asset<AudioClip> _13King => new("Assets/Game/Janken/Spine/Characters/King/mc/13_king.mp3");
        public static Asset<AudioClip> _14King => new("Assets/Game/Janken/Spine/Characters/King/mc/14_king.mp3");
        public static Asset<AudioClip> _15King => new("Assets/Game/Janken/Spine/Characters/King/mc/15_king.mp3");
        public static Asset<AudioClip> _16King => new("Assets/Game/Janken/Spine/Characters/King/mc/16_king.mp3");
        public static Asset<AudioClip> _01Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/01_macho.mp3");
        public static Asset<AudioClip> _02Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/02_macho.mp3");
        public static Asset<AudioClip> _03Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/03_macho.mp3");
        public static Asset<AudioClip> _04Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/04_macho.mp3");
        public static Asset<AudioClip> _05Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/05_macho.mp3");
        public static Asset<AudioClip> _06Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/06_macho.mp3");
        public static Asset<AudioClip> _07Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/07_macho.mp3");
        public static Asset<AudioClip> _08Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/08_macho.mp3");
        public static Asset<AudioClip> _09Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/09_macho.mp3");
        public static Asset<AudioClip> _10Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/10_macho.mp3");
        public static Asset<AudioClip> _11Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/11_macho.mp3");
        public static Asset<AudioClip> _12Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/12_macho.mp3");
        public static Asset<AudioClip> _13Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/13_macho.mp3");
        public static Asset<AudioClip> _14Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/14_macho.mp3");
        public static Asset<AudioClip> _15Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/15_macho.mp3");
        public static Asset<AudioClip> _16Macho => new("Assets/Game/Janken/Spine/Characters/Macho/mc/16_macho.mp3");
        public static Asset<AudioClip> _01Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/01_queen.mp3");
        public static Asset<AudioClip> _02Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/02_queen.mp3");
        public static Asset<AudioClip> _03Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/03_queen.mp3");
        public static Asset<AudioClip> _04Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/04_queen.mp3");
        public static Asset<AudioClip> _05Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/05_queen.mp3");
        public static Asset<AudioClip> _06Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/06_queen.mp3");
        public static Asset<AudioClip> _07Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/07_queen.mp3");
        public static Asset<AudioClip> _08Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/08_queen.mp3");
        public static Asset<AudioClip> _09Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/09_queen.mp3");
        public static Asset<AudioClip> _10Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/10_queen.mp3");
        public static Asset<AudioClip> _11Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/11_queen.mp3");
        public static Asset<AudioClip> _12Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/12_queen.mp3");
        public static Asset<AudioClip> _13Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/13_queen.mp3");
        public static Asset<AudioClip> _14Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/14_queen.mp3");
        public static Asset<AudioClip> _15Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/15_queen.mp3");
        public static Asset<AudioClip> _16Queen => new("Assets/Game/Janken/Spine/Characters/Queen/mc/16_queen.mp3");
        public static Asset<AudioClip> BgmRouletteLoop => new("Assets/Game/Roulette/Audios/bgm_roulette_loop.mp3");
        public static Asset<AudioClip> SfxRouletteBack => new("Assets/Game/Roulette/Audios/sfx_roulette_back.mp3");
        public static Asset<AudioClip> SfxRouletteConfirm => new("Assets/Game/Roulette/Audios/sfx_roulette_confirm.mp3");
        public static Asset<AudioClip> SfxRouletteGameDecelerating => new("Assets/Game/Roulette/Audios/sfx_roulette_game_decelerating.mp3");
        public static Asset<AudioClip> SfxRouletteGameRotating => new("Assets/Game/Roulette/Audios/sfx_roulette_game_rotating.mp3");
        public static Asset<AudioClip> SfxRouletteSelect => new("Assets/Game/Roulette/Audios/sfx_roulette_select.mp3");

    }
}