// This file is auto-generated by AssetsPostprocessor.
// Do not modify this file manually.
//
// To regenerate this file manually, select the menu item Tools > LunarFramework > Generate R.cs.
//

using Luna;
using UnityEngine;

namespace R
{
    public static class Audios
    {
        public static Asset<AudioClip> タンホイザーとアイーダメドレー => new("Assets/Game/Common/Commend/Audios/タンホイザーとアイーダメドレー.mp3");
        public static Asset<AudioClip> ハレルヤ => new("Assets/Game/Common/Commend/Audios/ハレルヤ.mp3");
        public static Asset<AudioClip> 威風堂々 => new("Assets/Game/Common/Commend/Audios/威風堂々.mp3");
        public static Asset<AudioClip> 拍手 => new("Assets/Game/Common/Commend/Audios/拍手.mp3");
        public static Asset<AudioClip> 指笛 => new("Assets/Game/Common/Commend/Audios/指笛.mp3");
        public static Asset<AudioClip> 歓声 => new("Assets/Game/Common/Commend/Audios/歓声.mp3");
        public static Asset<AudioClip> 見よ勇者は帰る => new("Assets/Game/Common/Commend/Audios/見よ、勇者は帰る.mp3");
        public static Asset<AudioClip> _01King => new("Assets/Game/Janken/Spine/King/mc/01_king.mp3");
        public static Asset<AudioClip> _02King => new("Assets/Game/Janken/Spine/King/mc/02_king.mp3");
        public static Asset<AudioClip> _03King => new("Assets/Game/Janken/Spine/King/mc/03_king.mp3");
        public static Asset<AudioClip> _04King => new("Assets/Game/Janken/Spine/King/mc/04_king.mp3");
        public static Asset<AudioClip> _05King => new("Assets/Game/Janken/Spine/King/mc/05_king.mp3");
        public static Asset<AudioClip> _06King => new("Assets/Game/Janken/Spine/King/mc/06_king.mp3");
        public static Asset<AudioClip> _07King => new("Assets/Game/Janken/Spine/King/mc/07_king.mp3");
        public static Asset<AudioClip> _08King => new("Assets/Game/Janken/Spine/King/mc/08_king.mp3");
        public static Asset<AudioClip> _09King => new("Assets/Game/Janken/Spine/King/mc/09_king.mp3");
        public static Asset<AudioClip> _10King => new("Assets/Game/Janken/Spine/King/mc/10_king.mp3");
        public static Asset<AudioClip> _11King => new("Assets/Game/Janken/Spine/King/mc/11_king.mp3");
        public static Asset<AudioClip> _12King => new("Assets/Game/Janken/Spine/King/mc/12_king.mp3");
        public static Asset<AudioClip> _13King => new("Assets/Game/Janken/Spine/King/mc/13_king.mp3");
        public static Asset<AudioClip> _14King => new("Assets/Game/Janken/Spine/King/mc/14_king.mp3");
        public static Asset<AudioClip> _15King => new("Assets/Game/Janken/Spine/King/mc/15_king.mp3");
        public static Asset<AudioClip> _16King => new("Assets/Game/Janken/Spine/King/mc/16_king.mp3");
        public static Asset<AudioClip> _01Queen => new("Assets/Game/Janken/Spine/Queen/mc/01_queen.mp3");
        public static Asset<AudioClip> _02Queen => new("Assets/Game/Janken/Spine/Queen/mc/02_queen.mp3");
        public static Asset<AudioClip> _03Queen => new("Assets/Game/Janken/Spine/Queen/mc/03_queen.mp3");
        public static Asset<AudioClip> _04Queen => new("Assets/Game/Janken/Spine/Queen/mc/04_queen.mp3");
        public static Asset<AudioClip> _05Queen => new("Assets/Game/Janken/Spine/Queen/mc/05_queen.mp3");
        public static Asset<AudioClip> _06Queen => new("Assets/Game/Janken/Spine/Queen/mc/06_queen.mp3");
        public static Asset<AudioClip> _07Queen => new("Assets/Game/Janken/Spine/Queen/mc/07_queen.mp3");
        public static Asset<AudioClip> _08Queen => new("Assets/Game/Janken/Spine/Queen/mc/08_queen.mp3");
        public static Asset<AudioClip> _09Queen => new("Assets/Game/Janken/Spine/Queen/mc/09_queen.mp3");
        public static Asset<AudioClip> _10Queen => new("Assets/Game/Janken/Spine/Queen/mc/10_queen.mp3");
        public static Asset<AudioClip> _11Queen => new("Assets/Game/Janken/Spine/Queen/mc/11_queen.mp3");
        public static Asset<AudioClip> _12Queen => new("Assets/Game/Janken/Spine/Queen/mc/12_queen.mp3");
        public static Asset<AudioClip> _13Queen => new("Assets/Game/Janken/Spine/Queen/mc/13_queen.mp3");
        public static Asset<AudioClip> _14Queen => new("Assets/Game/Janken/Spine/Queen/mc/14_queen.mp3");
        public static Asset<AudioClip> _15Queen => new("Assets/Game/Janken/Spine/Queen/mc/15_queen.mp3");
        public static Asset<AudioClip> _16Queen => new("Assets/Game/Janken/Spine/Queen/mc/16_queen.mp3");
        public static Asset<AudioClip> BgmRouletteLoop => new("Assets/Game/Roulette/Audios/bgm_roulette_loop.mp3");
        public static Asset<AudioClip> SfxRouletteBack => new("Assets/Game/Roulette/Audios/sfx_roulette_back.mp3");
        public static Asset<AudioClip> SfxRouletteConfirm => new("Assets/Game/Roulette/Audios/sfx_roulette_confirm.mp3");
        public static Asset<AudioClip> SfxRouletteGameDecelerating => new("Assets/Game/Roulette/Audios/sfx_roulette_game_decelerating.mp3");
        public static Asset<AudioClip> SfxRouletteGameRotating => new("Assets/Game/Roulette/Audios/sfx_roulette_game_rotating.mp3");
        public static Asset<AudioClip> SfxRouletteSelect => new("Assets/Game/Roulette/Audios/sfx_roulette_select.mp3");

    }
}